/*******************************************************************************
 * File Name: main.c
 *
 * Version: 1.10
 *
 *******************************************************************************/

#include <project.h>
#include <VDAC8.h>

#define REQUEST_PER_BURST (1u)
#define BYTES_PER_BURST (1u)
#define UPPER_SRC_ADDRESS CYDEV_PERIPH_BASE
#define UPPER_DEST_ADDRESS CYDEV_PERIPH_BASE

void DMA_Config(void);

/*******************************************************************************
 * Interrupt
 ********************************************************************************
 * Interrupt generated on Filter sample-ready. Interrupt handle:filterVDAC
 *
 * Summary:
 *  The interrupt performs following functions:
 *   1: Reads the left-justified register for Filter Channel A
 *   2: Converts it into an unsigned value
 *   3: Writes this value to VDAC
 *
 *******************************************************************************/
CY_ISR(filterVDAC)
{
    /* Convert the 2's complement value to an unsigned 8-bit value
     * The VDAC expects an unsigned 8-bit value as input.
     */
    VDAC8_SetValue(Filter_Read8(Filter_CHANNEL_A) + 128u);
}

/*******************************************************************************
* Function Name: main
********************************************************************************
*
* Summary:
*  Main function performs following functions:
*   1: Enables global interrupts
*   2: Start all components on the schematic
*   3: Calls a function to configure DMA

* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
int a = 200;
int Pin = 0;
int CountUp = 0;

int main()
{
    AMux_1_Init();
    WaveDAC8_1_Start();
    WaveDAC8_2_Start();
    ADC_DelSig_IRQ_Start();
    isr_StartEx(filterVDAC);
    ADC_DelSig_Start();
    ADC_DelSig_StartConvert();
    VDAC8_Start();
    // Opamp_Start();
    Filter_Start();

    /* User-implemented function to set-up DMA */
    DMA_Config();

    /* Enable Global Interrupts */
    CYGlobalIntEnable;

    WaveDAC8_1_Start();
    WaveDAC8_2_Stop();
    AMux_1_Select(0x00);
    Control_Reg_1_Write(0x00);
    CountUp = 1;
    //
    // Each time the switch is pushed, a new sine wave is sent to the filter
    //
    for (;;)
    {
        if (Pin_3_Read() == 0) // Is switch pushed?
        {
            if (CountUp == 0)
            {
                WaveDAC8_1_Start();
                WaveDAC8_2_Stop();
                AMux_1_Select(0x00);
                Control_Reg_1_Write(0x00);
                CountUp++;
            }
            else if (CountUp == 1)
            {
                Control_Reg_1_Write(0x01);
                CountUp++;
            }
            else if (CountUp == 2)
            {
                WaveDAC8_2_Start();
                WaveDAC8_1_Stop();
                AMux_1_Select(0x01);
                Control_Reg_1_Write(0x00);
                CountUp++;
            }
            else
            {
                CountUp = 0;
                Control_Reg_1_Write(0x02);
            }
            do
            {

            } while (Pin_3_Read() == 0);
        }
        CyDelay(100);
    }
}

/*******************************************************************************
 * Function Name: DMA_Config
 ********************************************************************************
 *
 * Summary:
 *  Initializes and sets up DMA for use (generated by DMA Wizard)
 *
 * Parameters:
 *  None.
 *
 * Return:
 *  None.
 *
 *******************************************************************************/
void DMA_Config(void)
{
    /* Declare variable to hold the handle for DMA channel */
    uint8 channelHandle;

    /* Declare DMA Transaction Descriptor for memory transfer into
     * Filter Channel.
     */
    uint8 tdChanA;

    /* Configure the DMA to Transfer the data in 1 burst with individual trigger
     * for each burst.
     */
    channelHandle = DMA_DmaInitialize(BYTES_PER_BURST, REQUEST_PER_BURST,
                                      HI16(UPPER_SRC_ADDRESS), HI16(UPPER_DEST_ADDRESS));

    /* This function allocates a TD for use with an initialized DMA channel */
    tdChanA = CyDmaTdAllocate();

    /* Configure the tdChanA to transfer 1 byte with no next TD */
    CyDmaTdSetConfiguration(tdChanA, 1u, DMA_INVALID_TD, 0u);

    /* Set the source address as ADC_DelSig and the destination as
     * Filter Channel A.
     */
    CyDmaTdSetAddress(tdChanA, LO16((uint32)ADC_DelSig_DEC_SAMP_PTR), LO16((uint32)Filter_STAGEAH_PTR));

    /* Set tdChanA to be the initial TD associated with channelHandle */
    CyDmaChSetInitialTd(channelHandle, tdChanA);

    /* Enable the DMA channel represented by channelHandle and preserve the TD */
    CyDmaChEnable(channelHandle, 1u);
}